### ISSUE TITLE
Auth applet

### ISSUE THREAD

**Issue by Kamirus** [purescript-webrow/webrow#6]
/login -> login form: email & password

/login?email&password -> check success -> create session -> OnSuccessfulLogin (Response -> Response)  HTTPure.Response set cookie redirect login successful  ()

/login?email&password -> check failure -> response LoginFailed

loginRequired - check whether the user is logged in
```
withLoginRequired do
  ...
```
/logout - similarly to the OnSuccessfulLogin remove cookie

**Comment by paluh** [comment]
We can say that initial prototyping phase is behind us:

https://github.com/purescript-webrow/webrow/tree/master/src/WebRow/Applets
